server:
  port: 8080
spring:
  application:
    name: "JavaEnvoyExtAuthz"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/e7c91a18-425d-4820-aedf-09d9c1c63cd7/v2.0
          jwk-set-uri: https://login.microsoftonline.com/e7c91a18-425d-4820-aedf-09d9c1c63cd7/discovery/v2.0/keys
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    org:
      springframework:
        security: DEBUG